source 'https://github.com/CocoaPods/Specs.git'
# platform: ios, ‘8.0’

target ‘QQLive’ do
	use_frameworks!
	pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'SVProgressHUD'
    pod 'BarrageRenderer'
    #pod 'GPUImage', '~> 0.1.7' LFLiveKit里面包含GPUImage
    pod 'LFLiveKit', '~> 1.6'
    pod 'HMSegmentedControl', '~> 1.5.3'
    
end
